name: Quality-check

on: pull_request

env:
  COVERAGE_FAIL_UNDER: 85

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.1'

      - name: Run flake8 style check
        run: poetry run flake8 app/

      - name: Run flake8 complexity check
        run: poetry run flake8 --max-complexity 10 app/

      - name: Run pytest with coverage check
        run: poetry run pytest --cov=app --cov-branch --cov-report=term --cov-fail-under=$COVERAGE_FAIL_UNDER
